version: '3'

services:
    nginx:
        image: nginx:latest
        ports:
            - 80:80
            - 443:443
        volumes:
            - ./nginx/conf.d/nginx.conf:/etc/nginx/conf.d/nginx.conf
            - ./public:/var/www/public
        restart: always
